### ISSUE TITLE
Create Hello World Sample for Python

### ISSUE THREAD

**Issue by captain-pool** [gnx-nsec/Hello-World#1]
Create Hello World Sample codes directory using python.
These are the sample programs to work on

- [ ] Printing Hello World
- [ ] Input name and greet the user as "Welcome, <name>"
- [ ] Print
```
      *
      *  *
      *  *  *
      *  *  *  *
```
using [for loop](https://www.w3schools.com/python/python_for_loops.asp)

**Comment by siddhantvirus** [comment]
Hi , I'll take this ! 
Let's also add Java and R ? 
Also , Do we want Three seperate codes ?

**Comment by alishashaw439** [comment]
Assign it to me.

**Comment by captain-pool** [comment]
@siddhantvirus you can collaborate with @alishashaw439 
You can submit for program 1 and program 2 whilist @alishashaw439 can work on program 3. I guess.
What do you say guys?

**Comment by alishashaw439** [comment]
I would really appreciate it.

**Comment by siddhantvirus** [comment]
Alright @alishashaw439 , Adding Program 1 and 2
