### ISSUE TITLE
Create Hello World Sample in R

### ISSUE THREAD

**Issue by captain-pool** [gnx-nsec/Hello-World#11]
Create Hello World Sample codes directory using R.
These are the sample programs to work on

- [ ] Printing Hello World
- [ ] Input name and greet the user as "Welcome, <name>"
- [ ] Print
```
      *
      *  *
      *  *  *
      *  *  *  *
```
using for loop

**Comment by sudeepta14** [comment]
Please assign this to me @captain-pool

**Comment by captain-pool** [comment]
Assigned! :)
