### ISSUE TITLE
 Create Hello World Sample for Javascript

### ISSUE THREAD

**Issue by captain-pool** [gnx-nsec/Hello-World#12]
Create Hello World Sample codes directory using Javascript.
These are the sample programs to work on

- [ ] Printing Hello World
- [ ] Input name and greet the user as "Welcome, <name>"
- [ ] Print
```
      *
      *  *
      *  *  *
      *  *  *  *
```
using for loop

**Comment by its-mayank** [comment]
Hey, I have done all 3 tasks in JS. Can I submit a pull request?

**Comment by captain-pool** [comment]
Solved in PR #19
