### ISSUE TITLE
Create Hello World Sample in C

### ISSUE THREAD

**Issue by captain-pool** [gnx-nsec/Hello-World#2]
Create Hello World Sample codes directory using C.
These are the sample programs to work on

- [ ] Printing Hello World
- [ ] Input name and greet the user as "Welcome, <name>"
- [ ] Print
```
      *
      *  *
      *  *  *
      *  *  *  *
```
using [for loop](https://www.tutorialspoint.com/cprogramming/c_for_loop.htm)

**Comment by yojeremiah** [comment]
I will handle this - please assign! :)

**Comment by Utkarsh2604** [comment]
would like to solve this @captain-pool

**Comment by Utkarsh2604** [comment]
Completed @captain-pool

**Comment by Zeocode** [comment]
I have sent a PR. Check it out. #45

**Comment by arkaprovaz** [comment]
Assign me

**Comment by Utkarsh2604** [comment]
i have completed it @captain-pool 
i have placed all files under one directory 
please **merge** my pr @captain-pool
