### ISSUE TITLE
Create Hello World Sample in C++

### ISSUE THREAD

**Issue by captain-pool** [gnx-nsec/Hello-World#3]
Create Hello World Sample codes directory using C++.
These are the sample programs to work on

- [ ] Printing Hello World
- [ ] Input name and greet the user as "Welcome, <name>"
- [ ] Print
```
      *
      *  *
      *  *  *
      *  *  *  *
```
using [for loop](https://www.tutorialspoint.com/cplusplus/cpp_for_loop.htm)

**Comment by yojeremiah** [comment]
I will handle this - please assign! :)

**Comment by VishalBheda** [comment]
added all three task, & requested PR  😉 😅
