### ISSUE TITLE
Hello World from Rust

### ISSUE THREAD

**Issue by wasthishelpful** [gnx-nsec/Hello-World#30]
Create Hello World Sample codes directory using rust.
These are the sample programs to work on

* [ ] Printing Hello World
* [ ] Input name and greet the user as "Welcome, "
* [ ] Print

      *
      *  *
      *  *  *
      *  *  *  *

using [for loop](https://doc.rust-lang.org/1.1.0/book/for-loops.html)

**Comment by wasthishelpful** [comment]
would like to solve this @captain-pool :)

**Comment by captain-pool** [comment]
@wasthishelpful assigning it to you. :)

**Comment by wasthishelpful** [comment]
see PR #34
