### ISSUE TITLE
Hello World in Kotlin

### ISSUE THREAD

**Issue by joardar-aditya** [gnx-nsec/Hello-World#36]
Create Hello World Sample codes directory using Kotlin.
These are the sample programs to work on

 

- [ ] Printing Hello World

 

- [ ] Input name and greet the user as "Welcome, "

 

- [ ] Print -
       *
       * *
       * * *
       * * * *
using for loop

**Comment by joardar-aditya** [comment]
assign it to me!

**Comment by captain-pool** [comment]
@joardar-aditya You're good to go!
