### ISSUE TITLE
Create Hello World Sample in C#.NET

### ISSUE THREAD

**Issue by captain-pool** [gnx-nsec/Hello-World#4]
Create Hello World Sample codes directory using C#.
These are the sample programs to work on

- [ ] Printing Hello World
- [ ] Input name and greet the user as "Welcome, <name>"
- [ ] Print
```
      *
      *  *
      *  *  *
      *  *  *  *
```
using [for loop](https://www.tutorialspoint.com/csharp/csharp_for_loop.htm)

**Comment by alishashaw439** [comment]
Assign it to me!
