### ISSUE TITLE
Create Hello World Sample in GO

### ISSUE THREAD

**Issue by Zeocode** [gnx-nsec/Hello-World#51]
Create Hello World Sample codes directory using GO.
These are the sample programs to work on

- [ ] Printing Hello World
- [ ] Input name and greet the user as "Welcome, "
- [ ] Print
```
      *
      *  *
      *  *  *
      *  *  *  *
```
using for loop

**Comment by Zeocode** [comment]
@captain-pool  Assign me this.

**Comment by captain-pool** [comment]
@Zeocode  you're good to go!

**Comment by Zeocode** [comment]
Done @captain-pool 
 #52 
:)
