### ISSUE TITLE
Create Hello World Sample in Scala

### ISSUE THREAD

**Issue by sparshag21** [gnx-nsec/Hello-World#68]
Create Hello World Sample codes directory using Scala.
These are the sample programs to work on

- Printing Hello World

- Input name and greet the user as "Welcome, "

- Print

```
*
* * 
* * * 
* * * * 
```
using for loop.

**Comment by sparshag21** [comment]
Please allow me to do this one too. :)

**Comment by captain-pool** [comment]
> Please allow me to do this one too. :)

@sparshag21 you're good to go.
