### ISSUE TITLE
Create Hello World Sample in Dart

### ISSUE THREAD

**Issue by captain-pool** [gnx-nsec/Hello-World#8]
Create Hello World Sample codes directory using Flutter (Dart).
These are the sample programs to work on

- [ ] Printing Hello World
- [ ] Input name and greet the user as "Welcome, <name>"
- [ ] Print
```
      *
      *  *
      *  *  *
      *  *  *  *
```
using [for loop](https://flutterrdart.com/dart-for-in-loop-code-with-examples/)

**Comment by alishashaw439** [comment]
assign it to me

**Comment by bosecodes** [comment]
Assign it to me!!!

**Comment by joardar-aditya** [comment]
Already solved!!
