### ISSUE TITLE
 Create Hello World Sample for Java

### ISSUE THREAD

**Issue by captain-pool** [gnx-nsec/Hello-World#9]
Create Hello World Sample codes directory using Java.
These are the sample programs to work on

- [ ] Printing Hello World
- [ ] Input name and greet the user as "Welcome, <name>"
- [ ] Print
```
      *
      *  *
      *  *  *
      *  *  *  *
```
using [for loop](https://www.javatpoint.com/java-for-loop)

**Comment by alishashaw439** [comment]
assign this to me

**Comment by joardar-aditya** [comment]
assign it to me!!!

**Comment by captain-pool** [comment]
@joardar-aditya it is already assigned and a pull request has already been dropped.

https://github.com/gnx-nsec/Hello-World/commit/9c78ad45f3738e843b4a74c76203e608aaac99d5
